import "wtypes.idl";
[
    uuid(7d3e78bd-0472-4736-8797-e64e966d692e),
    version(1.0),
    pointer_default(unique)
]
interface vdm_service
{
    typedef [context_handle] void *VDM_CONNECTION;
    error_status_t Connect(
        [in] handle_t binding,
        [in, system_handle(sh_process)] HANDLE process,
        [out] VDM_CONNECTION *connection,
        [out] unsigned long *generation);
    error_status_t First(
        [in] handle_t binding,
        [in] VDM_CONNECTION connection,
        [in, system_handle(sh_process)] HANDLE process,
        [in] unsigned long generation,
        [out] unsigned long *first);
    error_status_t Disconnect(
        [in] handle_t binding,
        [in, system_handle(sh_process)] HANDLE process,
        [in] unsigned long generation,
        [in,out] VDM_CONNECTION *connection);
}
