#ifndef NTDOS64_HISTORICAL_DEM_BYOB_PROFILE_V1_H
#define NTDOS64_HISTORICAL_DEM_BYOB_PROFILE_V1_H

int __cdecl ntdos64_historical_dem_byob_profile_v1_replace_directory(const char *directory);

#endif
