#ifndef NTCON_TEXT_FRAME_H
#define NTCON_TEXT_FRAME_H
#include <windows.h>
#include "interface/console_video.h"

/* Backend-local conversion. The result uses the unchanged NTVDM wire ABI;
 * release *payload with HeapFree. Fonts are supplied by the backend's current
 * admitted font state, never selected or generated by the frontend. */
DWORD ntcon_text_frame_pack(const CONSOLE_SCREEN_BUFFER_INFOEX *,
    const CONSOLE_CURSOR_INFO *,const CHAR_INFO *,SIZE_T,
    const console_text_style *,console_video_description *,BYTE **payload);
#endif
