#ifndef NTVWM_TEXT_FRAME_H
#define NTVWM_TEXT_FRAME_H
#include <windows.h>
#include "common/protocol/console_video.h"
#include "common/protocol/console_mouse.h"

typedef struct ntvwm_mouse {
    SMALL_RECT viewport;
    LONG x,y;
    unsigned font_height;
    DWORD buttons;
    BOOL ready,visible;
} ntvwm_mouse;
DWORD ntvwm_mouse_geometry(ntvwm_mouse *,SMALL_RECT,unsigned);
DWORD ntvwm_mouse_input(ntvwm_mouse *,const console_frame_mouse_input *,INPUT_RECORD [2],DWORD *);
void ntvwm_mouse_compose(const ntvwm_mouse *,const console_video_description *,BYTE *);

/* Backend-local conversion. The result uses the unchanged NTVDM wire ABI;
 * release *payload with HeapFree. Fonts are supplied by the backend's current
 * admitted font state, never selected or generated by the frontend. */
DWORD ntvwm_text_frame_pack(const CONSOLE_SCREEN_BUFFER_INFOEX *,
    const CONSOLE_CURSOR_INFO *,const CHAR_INFO *,SIZE_T,
    const console_text_style *,console_video_description *,BYTE **payload);
#endif
