#include "bx_ntvdm_boot_namespace_plane_v1.h"
#include <string.h>

static void win(bx_ntvdm_instruction_window_v1 *w,uint8_t x,uint8_t y){uint8_t b[]={0xc4,0xc4,x,y};bx_ntvdm_instruction_window_v1_capture(w,b,4);}
static int route(bx_ntvdm_instruction_window_v1 *w,bx_ntvdm_bop_ingress_v1 *i,bx_ntvdm_bop_provider_selection_v1 *s){return bx_ntvdm_bop_ingress_v1_classify(w,i)&&bx_ntvdm_bop_provider_registry_v1_select(i,s);}
int main(void){uint8_t c[]={0x90,0xc3},t[]={0xf4};byob_image ci={c,2},ti={t,1};byob_profile_selection q={0};bx_ntvdm_boot_namespace_plane_v1 p;bx_ntvdm_exception_event_v1 e={BX_NTVDM_EXCEPTION_ABI_MAGIC,1,sizeof(e),1,0,6,0,0,0x100};bx_ntvdm_cpu_state_v1 cpu;bx_ntvdm_instruction_window_v1 w;bx_ntvdm_bop_ingress_v1 i;bx_ntvdm_bop_provider_selection_v1 s;struct bx_ntvdm_mechanical_action_v1 a,n;bx_ntvdm_cpu_result_v2 r;uint32_t token;
 wcscpy(q.command_placement.path,L"\\COMMAND.COM");q.command_placement.drive_index=2;q.has_command_placement=1;wcscpy(q.target_placement.path,L"\\TARGET.COM");q.target_placement.drive_index=2;q.has_target_placement=1;wcscpy(q.target.file_name,L"TARGET.COM");wcscpy(q.config_file.path,L"\\CONFIG.SYS");q.config_file.materialization=BYOB_GUEST_BOOT_FILE_MINIMAL_COMMENT_V1;wcscpy(q.autoexec_file.path,L"\\AUTOEXEC.BAT");q.autoexec_file.materialization=BYOB_GUEST_BOOT_FILE_EMPTY_V1;q.has_guest_boot_files=1;q.has_guest_search_metadata=1;q.command_metadata.attributes=q.target_metadata.attributes=q.config_metadata.attributes=q.autoexec_metadata.attributes=0x20u;q.command_metadata.dos_date=q.target_metadata.dos_date=q.config_metadata.dos_date=q.autoexec_metadata.dos_date=1u;
 if(!bx_ntvdm_boot_namespace_plane_v1_initialize(&p,&ci,&ti,0,&q))return 1;bx_ntvdm_cpu_state_v1_initialize(&cpu,BX_NTVDM_CPU_EXECUTION_REAL);cpu.ds=0x1000;cpu.edx=0x20;win(&w,0x54,0x0c);if(!route(&w,&i,&s)||!bx_ntvdm_boot_namespace_plane_v1_dispatch(&p,&i,&s,&e,&cpu,&w,&a,&r)||a.kind!=BX_NTVDM_MECHANICAL_ACTION_V1_WRITE)return 2;
 cpu.esi=0x40;win(&w,0x50,0x12);if(!route(&w,&i,&s)||!bx_ntvdm_boot_namespace_plane_v1_dispatch(&p,&i,&s,&e,&cpu,&w,&a,&r)||a.kind!=BX_NTVDM_MECHANICAL_ACTION_V1_READ||a.payload_bytes!=128)return 3;memcpy(a.payload,"C:\\CONFIG.SYS",14);if(!bx_ntvdm_boot_namespace_plane_v1_complete_read(&p,&a,&n,&r)||r.disposition!=BX_NTVDM_CPU_RESULT_V2_RESUME||n.kind!=BX_NTVDM_MECHANICAL_ACTION_V1_NONE)return 4;token=((uint32_t)r.cpu_delta.gpr16_values[5]<<16)|r.cpu_delta.gpr16_values[0];cpu.eax=token&0xffffu;cpu.ebp=token>>16;cpu.ecx=20;cpu.edx=0x80;cpu.eflags=0x40;win(&w,0x50,0x16);if(!route(&w,&i,&s))return 51;if(!bx_ntvdm_boot_namespace_plane_v1_dispatch(&p,&i,&s,&e,&cpu,&w,&a,&r))return 52;if(a.kind!=BX_NTVDM_MECHANICAL_ACTION_V1_WRITE)return 100+(r.cpu_delta.gpr16_values[0]&0x7fu);if(!a.payload_bytes)return 54;win(&w,0x50,0x09);if(!route(&w,&i,&s)||!bx_ntvdm_boot_namespace_plane_v1_dispatch(&p,&i,&s,&e,&cpu,&w,&a,&r)||a.kind!=BX_NTVDM_MECHANICAL_ACTION_V1_NONE)return 6;return 0;}
