#include "bx_ntvdm_command_package_session_v1.h"
#include "bx_ntvdm_bop_provider_registry_v1.h"
#include "bx-mantle/bx_ntvdm_mechanical_action_v1.h"
#include <string.h>

static uint8_t ram[0x100000];
int bx_ntvdm_mantle_execute_mechanical_action_v1(struct bx_ntvdm_mechanical_action_v1 *a)
{ uint32_t i; if(!bx_ntvdm_mechanical_action_v1_valid(a))return 0;
  for(i=0;i<a->range_count;i++){const struct bx_ntvdm_mechanical_action_v1_range *r=&a->ranges[i];if(r->physical_address>sizeof(ram)-r->byte_count)return 0;if(a->kind==BX_NTVDM_MECHANICAL_ACTION_V1_READ)memcpy(a->payload+r->payload_offset,ram+r->physical_address,r->byte_count);else if(a->kind==BX_NTVDM_MECHANICAL_ACTION_V1_WRITE)memcpy(ram+r->physical_address,a->payload+r->payload_offset,r->byte_count);else return 0;}return 1; }
static int fake_calls;
static int fake_backend(const bx_ntvdm_command_child_backend_v1_request *q,bx_ntvdm_command_child_backend_v1_result *r)
{ if(!bx_ntvdm_command_child_backend_v1_request_valid(q)||!r)return 0; ++fake_calls;bx_ntvdm_command_child_backend_v1_result_clear(r);r->completed=1u;r->exit_code=q->launch_service==8u?31u:32u;return bx_ntvdm_command_child_backend_v1_result_valid(r); }
static void selection_init(byob_profile_selection *s)
{ memset(s,0,sizeof(*s));memcpy(s->command_placement.path,L"\\COMMAND.COM",sizeof(L"\\COMMAND.COM"));s->command_placement.drive_index=2u;s->has_command_placement=1u;memcpy(s->target_placement.path,L"\\TARGET.COM",sizeof(L"\\TARGET.COM"));s->target_placement.drive_index=2u;s->has_target_placement=1u;s->declared_target_count=1u;memcpy(s->declared_targets[0].component.file_name,L"TARGET.COM",sizeof(L"TARGET.COM"));memcpy(s->declared_targets[0].placement.path,L"\\TARGET.COM",sizeof(L"\\TARGET.COM"));s->declared_targets[0].placement.drive_index=2u;memcpy(s->target.file_name,L"TARGET.COM",sizeof(L"TARGET.COM"));memcpy(s->config_file.path,L"\\CONFIG.SYS",sizeof(L"\\CONFIG.SYS"));s->config_file.materialization=BYOB_GUEST_BOOT_FILE_MINIMAL_COMMENT_V1;memcpy(s->autoexec_file.path,L"\\AUTOEXEC.BAT",sizeof(L"\\AUTOEXEC.BAT"));s->autoexec_file.materialization=BYOB_GUEST_BOOT_FILE_EMPTY_V1;s->has_guest_boot_files=s->has_guest_search_metadata=1u;s->command_metadata.attributes=s->target_metadata.attributes=s->config_metadata.attributes=s->autoexec_metadata.attributes=0x20u;s->command_metadata.dos_date=s->target_metadata.dos_date=s->config_metadata.dos_date=s->autoexec_metadata.dos_date=1u; }
static int profile_init(bx_ntvdm_mutation_profile_v1 *p,uint32_t m)
{ bx_ntvdm_mutation_profile_v1_initialize(p,m);return bx_ntvdm_command_profile_consumer_v1_register_class(p,BX_NTVDM_MUTATION_CLASS_V1_HOST_GLOBAL,0x03u); }
static void event_init(bx_ntvdm_exception_event_v1 *e)
{ *e=(bx_ntvdm_exception_event_v1){BX_NTVDM_EXCEPTION_ABI_MAGIC,BX_NTVDM_EXCEPTION_ABI_VERSION,sizeof(*e),BX_NTVDM_EXCEPTION_EVENT_CPU_EXCEPTION,0u,6u,0u,0u,0x200u}; }
static int invoke(bx_ntvdm_command_package_session_v1 *s,bx_ntvdm_exception_event_v1 *e,bx_ntvdm_cpu_state_v1 *c,uint8_t svc,bx_ntvdm_cpu_result_v2 *r)
{ uint8_t b[4]={0xc4u,0xc4u,0x54u,svc};bx_ntvdm_instruction_window_v1 w;bx_ntvdm_bop_ingress_v1 i;bx_ntvdm_bop_provider_selection_v1 p;bx_ntvdm_instruction_window_v1_capture(&w,b,sizeof(b));return bx_ntvdm_bop_ingress_v1_classify(&w,&i)&&bx_ntvdm_bop_provider_registry_v1_select(&i,&p)&&bx_ntvdm_command_package_session_v1_dispatch(s,&i,&p,e,c,&w,r); }
static uint32_t stream_token(bx_ntvdm_command_package_session_v1 *s,bx_ntvdm_exception_event_v1 *e,bx_ntvdm_cpu_state_v1 *c,uint32_t slot)
{ bx_ntvdm_cpu_result_v2 r; c->ecx=slot;
  if(!invoke(s,e,c,6u,&r)||r.disposition!=BX_NTVDM_CPU_RESULT_V2_RESUME||(r.eflags_values&BX_NTVDM_CPU_RESULT_V2_EFLAGS_CF)!=0u)return 0u;
  return ((uint32_t)r.cpu_delta.gpr16_values[3]<<16u)|r.cpu_delta.gpr16_values[1]; }
static int setup(bx_ntvdm_command_package_session_v1 *s,bx_ntvdm_boot_namespace_plane_v1 *n,bx_ntvdm_dem_gset_plane_v1 *g,bx_ntvdm_mutation_profile_v1 *p,uint32_t mode)
{ uint8_t a[]={0xf4},b[]={0xf4},c[]={0xf4};byob_image nt={a,sizeof(a)},co={b,sizeof(b)},ta={c,sizeof(c)};byob_profile_selection x;bx_ntvdm_command_host_context_v1 h;static const uint8_t env[]={ 'A','=','1',0,0};static const uint8_t proc[]="COMMAND.COM";selection_init(&x);bx_ntvdm_dem_gset_plane_v1_clear(g);if(!bx_ntvdm_boot_namespace_plane_v1_initialize(n,&nt,&co,&ta,0,&x)||!bx_ntvdm_command_package_session_v1_initialize(s,n,g)||!profile_init(p,mode)||!bx_ntvdm_command_package_session_v1_set_mutation_profile(s,p)||!bx_ntvdm_command_host_context_v1_initialize(&h,2u,(const uint8_t *)"C:\\",3u)||!bx_ntvdm_command_host_context_v1_set_environment(&h,env,sizeof(env))||!bx_ntvdm_command_host_context_v1_set_processor(&h,proc,sizeof(proc))||!bx_ntvdm_command_package_session_v1_set_host_context(s,&h))return 0;s->launch_execution_provider.child_redirection.execute=fake_backend;return 1; }
int main(void)
{ bx_ntvdm_command_package_session_v1 s;bx_ntvdm_boot_namespace_plane_v1 n;bx_ntvdm_dem_gset_plane_v1 g;bx_ntvdm_mutation_profile_v1 p;bx_ntvdm_exception_event_v1 e;bx_ntvdm_cpu_state_v1 c;bx_ntvdm_cpu_result_v2 r;uint32_t before,tokens[3];uint8_t handles[12];
  memset(ram,0,sizeof(ram));event_init(&e);bx_ntvdm_cpu_state_v1_initialize(&c,BX_NTVDM_CPU_EXECUTION_REAL);c.es=0x20u;if(!setup(&s,&n,&g,&p,BX_NTVDM_MUTATION_MODE_V1_DIRECT))return 1;memcpy(ram+0x200u,"A=1\0\0",5u);if(!invoke(&s,&e,&c,10u,&r)||r.cpu_delta.gpr16_values[0]!=32u||fake_calls!=1)return 2;if(!invoke(&s,&e,&c,11u,&r)||r.cpu_delta.gpr16_values[0]!=32u||s.launch_execution_provider.child_redirection.completion_consumed!=1u)return 3;
  if(!bx_ntvdm_command_package_session_v1_admit_cli_streams(&s))return 4;c.ds=0x300u;c.es=0x400u;c.ss=0x500u;c.esi=0x10u;c.ebp=0x20u;memcpy(ram+0x3010u,"COMMAND.COM /C EXIT\r",20u);memcpy(ram+0x4000u,"A=1\0\0",5u);tokens[0]=stream_token(&s,&e,&c,0u);tokens[1]=stream_token(&s,&e,&c,1u);tokens[2]=stream_token(&s,&e,&c,2u);if(!tokens[0]||!tokens[1]||!tokens[2])return 5;memcpy(handles+0u,&tokens[2],4u);memcpy(handles+4u,&tokens[1],4u);memcpy(handles+8u,&tokens[0],4u);memcpy(ram+0x5020u,handles,sizeof(handles));if(!invoke(&s,&e,&c,8u,&r)||r.cpu_delta.gpr16_values[0]!=31u||fake_calls!=2||s.launch_execution_provider.child_redirection.completion_present!=1u)return 6;if(!invoke(&s,&e,&c,11u,&r)||r.cpu_delta.gpr16_values[0]!=31u||s.launch_execution_provider.child_redirection.completion_consumed!=1u)return 7;
  before=(uint32_t)fake_calls;if(!setup(&s,&n,&g,&p,BX_NTVDM_MUTATION_MODE_V1_READONLY))return 8;if(!invoke(&s,&e,&c,8u,&r)||r.cpu_delta.gpr16_values[0]!=50u||fake_calls!=(int)before)return 9;if(!invoke(&s,&e,&c,10u,&r)||r.cpu_delta.gpr16_values[0]!=50u||fake_calls!=(int)before)return 10;if(!setup(&s,&n,&g,&p,BX_NTVDM_MUTATION_MODE_V1_OVERLAY))return 11;if(!invoke(&s,&e,&c,8u,&r)||r.cpu_delta.gpr16_values[0]!=50u||fake_calls!=(int)before)return 12;if(!setup(&s,&n,&g,&p,BX_NTVDM_MUTATION_MODE_V1_VIRTUAL))return 13;if(!invoke(&s,&e,&c,10u,&r)||r.cpu_delta.gpr16_values[0]!=50u||fake_calls!=(int)before)return 14;return 0; }