#include "bop/shim/command_misc_shim.h"
#include <stdio.h>
#include <string.h>

typedef struct fixture_context { uint8_t guest[0x10000]; } fixture_context;
static int read_guest(void *state,uint32_t address,uint8_t *buffer,uint32_t bytes)
{ fixture_context *context=(fixture_context *)state; if(!context||address>sizeof(context->guest)||bytes>sizeof(context->guest)-address)return 0;memcpy(buffer,context->guest+address,bytes);return 1; }
static int write_guest(void *state,uint32_t address,const uint8_t *buffer,uint32_t bytes)
{ fixture_context *context=(fixture_context *)state; if(!context||address>sizeof(context->guest)||bytes>sizeof(context->guest)-address)return 0;memcpy(context->guest+address,buffer,bytes);return 1; }
static void event_initialize(bx_ntvdm_exception_event_v1 *event)
{ memset(event,0,sizeof(*event));event->magic=BX_NTVDM_EXCEPTION_ABI_MAGIC;event->abi_version=BX_NTVDM_EXCEPTION_ABI_VERSION;event->struct_bytes=sizeof(*event);event->kind=BX_NTVDM_EXCEPTION_EVENT_CPU_EXCEPTION;event->vector=6u;event->fault_rip=0x500u; }
static int invoke(fixture_context *context,bx_ntvdm_exception_event_v1 *event,bx_ntvdm_cpu_state_v1 *cpu,bx_ntvdm_cpu_result_v2 *result,bx_ntvdm_command_misc_session *session,uint32_t service)
{ bx_ntvdm_command_misc_call call;memset(&call,0,sizeof(call));call.magic=BX_NTVDM_COMMAND_MISC_CALL_MAGIC;call.abi_version=BX_NTVDM_COMMAND_MISC_CALL_VERSION;call.struct_bytes=sizeof(call);call.service=service;call.boundary=event;call.cpu=cpu;call.result=result;call.guest_state=context;call.guest_read=read_guest;call.guest_write=write_guest;call.session=session;return bx_ntvdm_command_misc_invoke(&call); }
int main(void)
{
 fixture_context context;bx_ntvdm_exception_event_v1 event;bx_ntvdm_cpu_state_v1 cpu;bx_ntvdm_cpu_result_v2 result;bx_ntvdm_command_misc_session session;CHAR old_comspec[MAX_PATH],test_comspec[MAX_PATH],pipe_text[64],current_directory[MAX_PATH + 1u];DWORD old_bytes,pipe_bytes,error,current_directory_bytes;uint32_t standard_handle;uint32_t *standard;HANDLE pipe_read,pipe_write;SECURITY_ATTRIBUTES security;VDMINFO directory_info;CHAR current_directory_name[4]="=?:";
 memset(&context,0,sizeof(context));event_initialize(&event);bx_ntvdm_cpu_state_v1_initialize(&cpu,BX_NTVDM_CPU_EXECUTION_REAL);bx_ntvdm_command_misc_session_initialize(&session);
 current_directory_bytes=GetCurrentDirectoryA((DWORD)sizeof(current_directory),current_directory);if(current_directory_bytes==0u||current_directory_bytes>=sizeof(current_directory)||current_directory[1]!=':')return 10;current_directory_name[1]=(CHAR)((current_directory[0]>='a'&&current_directory[0]<='z')?current_directory[0]-'a'+'A':current_directory[0]);if(current_directory_name[1]<'A'||current_directory_name[1]>'Z')return 11;memset(&directory_info,0,sizeof(directory_info));directory_info.CurDrive=(USHORT)(current_directory_name[1]-'A');directory_info.CurDirectory=current_directory;directory_info.CurDirectoryLen=(USHORT)current_directory_bytes;cmdSetDirectories(NULL,&directory_info);
 cpu.ds=0x100u;cpu.esi=0u;cpu.es=0x200u;cpu.ss=0x600u;cpu.ebp=0u;cpu.eax=0x0102u;standard=(uint32_t *)(context.guest+0x6000u);standard[0]=standard[1]=standard[2]=UINT32_MAX;memcpy(context.guest+0x1000u,"exit 37\r",8u);memcpy(context.guest+0x2000u,"ENV=",4u);memset(context.guest+0x2004u,'L',1300u);context.guest[0x2518u]=context.guest[0x2519u]=0u;
 if(!invoke(&context,&event,&cpu,&result,&session,BX_NTVDM_COMMAND_MISC_EXEC)||result.disposition!=BX_NTVDM_CPU_RESULT_V2_RESUME||(result.eflags_values&BX_NTVDM_CPU_RESULT_V2_EFLAGS_CF)!=0u||result.cpu_delta.gpr16_values[0]!=(0x0100u|37u)||context.guest[0x1007u]!=0u)return 1;
 old_bytes=GetEnvironmentVariableA("COMSPEC",old_comspec,sizeof(old_comspec));if(old_bytes==0u||old_bytes>=sizeof(old_comspec))return 2;_snprintf_s(test_comspec,sizeof(test_comspec),_TRUNCATE,"%s /c exit 41",old_comspec);if(!SetEnvironmentVariableA("COMSPEC",test_comspec))return 3;
 cpu.eax=0x0002u;cpu.es=0x200u;if(!invoke(&context,&event,&cpu,&result,&session,BX_NTVDM_COMMAND_MISC_EXEC_COMSPEC32)||result.disposition!=BX_NTVDM_CPU_RESULT_V2_RESUME||(result.eflags_values&BX_NTVDM_CPU_RESULT_V2_EFLAGS_CF)!=0u||result.cpu_delta.gpr16_values[0]!=(0x0000u|41u)){SetEnvironmentVariableA("COMSPEC",old_comspec);return 4;}SetEnvironmentVariableA("COMSPEC",old_comspec);
 /* Current-directory publication is independently owned by T234's
  * command-set-directories fixture. Keep this lifecycle test focused on the
  * imported child/return contract. */
 cpu.edx=0x22u;cpu.eax=(uint32_t)(current_directory_name[1]-'A');cpu.ebx=0u;cpu.ecx=0u;if(!invoke(&context,&event,&cpu,&result,&session,BX_NTVDM_COMMAND_MISC_RETURN_EXIT_CODE)||result.disposition!=BX_NTVDM_CPU_RESULT_V2_RESUME||(result.eflags_values&BX_NTVDM_CPU_RESULT_V2_EFLAGS_CF)!=0u||result.cpu_delta.gpr16_values[0]!=(0x0000u|41u))return 5;
 security.nLength=sizeof(security);security.lpSecurityDescriptor=NULL;security.bInheritHandle=TRUE;if(!CreatePipe(&pipe_read,&pipe_write,&security,0u)||!SetHandleInformation(pipe_read,HANDLE_FLAG_INHERIT,0u))return 6;session.handles.next_guest_handle=0x10000u;if(!bx_ntvdm_host_handle_manager_publish(&session.handles,pipe_write,BX_NTVDM_HOST_HANDLE_BORROWED,&standard_handle,&error)||standard_handle!=0x10000u){CloseHandle(pipe_read);CloseHandle(pipe_write);return 6;}standard[0]=UINT32_MAX;standard[1]=standard_handle+0x10000u;standard[2]=UINT32_MAX;cpu.eax=0x0102u;memcpy(context.guest+0x1000u,"echo TOKEN\r",11u);if(!invoke(&context,&event,&cpu,&result,&session,BX_NTVDM_COMMAND_MISC_EXEC)||result.disposition!=BX_NTVDM_CPU_RESULT_V2_RESUME||(result.eflags_values&BX_NTVDM_CPU_RESULT_V2_EFLAGS_CF)!=0u||(result.cpu_delta.gpr16_values[0]&0xffu)!=(ERROR_INVALID_HANDLE&0xffu)){bx_ntvdm_host_handle_manager_release(&session.handles,standard_handle,&error);CloseHandle(pipe_read);CloseHandle(pipe_write);return 7;}standard[1]=standard_handle;memcpy(context.guest+0x1000u,"echo TOKEN\r",11u);if(!invoke(&context,&event,&cpu,&result,&session,BX_NTVDM_COMMAND_MISC_EXEC)||result.disposition!=BX_NTVDM_CPU_RESULT_V2_RESUME||(result.eflags_values&BX_NTVDM_CPU_RESULT_V2_EFLAGS_CF)!=0u){bx_ntvdm_host_handle_manager_release(&session.handles,standard_handle,&error);CloseHandle(pipe_read);CloseHandle(pipe_write);return 8;}if(!bx_ntvdm_host_handle_manager_release(&session.handles,standard_handle,&error)){CloseHandle(pipe_read);CloseHandle(pipe_write);return 8;}CloseHandle(pipe_write);memset(pipe_text,0,sizeof(pipe_text));if(!ReadFile(pipe_read,pipe_text,sizeof(pipe_text)-1u,&pipe_bytes,NULL)||strstr(pipe_text,"TOKEN")==NULL){CloseHandle(pipe_read);return 9;}CloseHandle(pipe_read);
 bx_ntvdm_host_handle_manager_reset(&session.handles);puts("T231 S8 direct OpenNT command lifecycle execute, COMSPEC, return, guest-tail, and standard-handle token behavior verified");return 0;
}
