#ifndef BX_NTVDM_COMMAND_CONSOLE_CAPABILITY_V1_H
#define BX_NTVDM_COMMAND_CONSOLE_CAPABILITY_V1_H
#include "bx_ntvdm_cpu_result_v2.h"
#include "bx_ntvdm_exception_abi.h"
#define BX_NTVDM_COMMAND_CONSOLE_CAPABILITY_V1_MAGIC 0x4258434fu
#define BX_NTVDM_COMMAND_CONSOLE_CAPABILITY_V1_VERSION 1u
typedef struct bx_ntvdm_command_console_capability_v1 { uint32_t magic, abi_version, struct_bytes, started_new_console, initialized, reserved0; } bx_ntvdm_command_console_capability_v1;
void bx_ntvdm_command_console_capability_v1_initialize(bx_ntvdm_command_console_capability_v1 *v,uint32_t n);
int bx_ntvdm_command_console_capability_v1_valid(const bx_ntvdm_command_console_capability_v1 *v);
int bx_ntvdm_command_console_capability_v1_dispatch(bx_ntvdm_command_console_capability_v1 *v,const bx_ntvdm_exception_event_v1 *e,const bx_ntvdm_cpu_state_v1 *c,const bx_ntvdm_instruction_window_v1 *w,bx_ntvdm_cpu_result_v2 *r);
#endif
