#include "bx_ntvdm_cmd_comspec_bootstrap_service.h"
#include <string.h>

#define APERTURE UINT64_C(0x100000)
static int match(const bx_ntvdm_exception_event_v1 *e,const bx_ntvdm_cpu_state_v1 *c,const bx_ntvdm_instruction_window_v1 *w,uint8_t svc){return e&&c&&w&&bx_ntvdm_exception_event_v1_valid(e)&&bx_ntvdm_cpu_state_v1_valid(c)&&bx_ntvdm_instruction_window_v1_valid(w)&&e->vector==6u&&c->execution_mode==BX_NTVDM_CPU_EXECUTION_REAL&&w->valid_bytes>=4u&&w->bytes[0]==0xc4u&&w->bytes[1]==0xc4u&&w->bytes[2]==0x54u&&w->bytes[3]==svc&&e->fault_rip<=UINT64_MAX-4u;}
void bx_ntvdm_cmd_comspec_bootstrap_v1_initialize(bx_ntvdm_cmd_comspec_bootstrap_v1 *v){if(v)memset(v,0,sizeof(*v));}
int bx_ntvdm_cmd_comspec_bootstrap_v1_prepare_comspec(const bx_ntvdm_readonly_namespace_v1 *n,const bx_ntvdm_exception_event_v1 *e,const bx_ntvdm_cpu_state_v1 *c,const bx_ntvdm_instruction_window_v1 *w,const bx_ntvdm_cmd_comspec_bootstrap_v1 *s,bx_ntvdm_guest_gather_read_action_v1 *a){bx_ntvdm_guest_range r;uint64_t addr;if(!n||!s||s->ready||!a||!match(e,c,w,2u))return 0;addr=((uint64_t)c->ds<<4)+(uint16_t)c->edx;if(addr>APERTURE-BX_NTVDM_CMD_COMSPEC_TEXT_MAX_BYTES)return 0;r.address=addr;r.length=BX_NTVDM_CMD_COMSPEC_TEXT_MAX_BYTES;return bx_ntvdm_guest_gather_read_action_v1_need_read_resume(a,&r,1u,e->fault_rip+4u);}
int bx_ntvdm_cmd_comspec_bootstrap_v1_complete_comspec(const bx_ntvdm_readonly_namespace_v1 *n,const bx_ntvdm_exception_event_v1 *e,const bx_ntvdm_cpu_state_v1 *c,const bx_ntvdm_guest_gather_read_action_v1 *a,const uint8_t *b,uint64_t count,bx_ntvdm_cmd_comspec_bootstrap_v1 *s,bx_ntvdm_cpu_result_v2 *r){uint32_t bytes,ax;if(!n||!s||s->ready||!r||!a||!b||count!=BX_NTVDM_CMD_COMSPEC_TEXT_MAX_BYTES||!bx_ntvdm_guest_gather_read_action_v1_valid(a)||a->disposition!=BX_NTVDM_GUEST_GATHER_READ_ACTION_V1_NEED_READ||a->range_count!=1u||a->total_bytes!=BX_NTVDM_CMD_COMSPEC_TEXT_MAX_BYTES||a->cpu_result.disposition!=BX_NTVDM_CPU_RESULT_V2_RESUME||a->cpu_result.resume_rip!=e->fault_rip+4u)return 0;for(bytes=0u;bytes<BX_NTVDM_CMD_COMSPEC_TEXT_MAX_BYTES;++bytes)if(b[bytes]==0u)break;if(bytes==BX_NTVDM_CMD_COMSPEC_TEXT_MAX_BYTES)return 0;memcpy(s->environment,"COMSPEC=",8u);memcpy(s->environment+8u,b,bytes+1u);s->environment_bytes=8u+bytes+1u;s->ready=1u;ax=(uint16_t)((c->eax&0xff00u)|1u);return bx_ntvdm_cpu_result_v2_resume(r,a->cpu_result.resume_rip)&&bx_ntvdm_cpu_delta_v1_set_gpr16(&r->cpu_delta,0u,(uint16_t)ax);}
int bx_ntvdm_cmd_comspec_bootstrap_v1_prepare_environment(const bx_ntvdm_exception_event_v1 *e,const bx_ntvdm_cpu_state_v1 *c,const bx_ntvdm_instruction_window_v1 *w,const bx_ntvdm_cmd_comspec_bootstrap_v1 *s,bx_ntvdm_multi_write_transaction_v1 *t,uint8_t p[BX_NTVDM_MULTI_WRITE_MAX_PAYLOAD]){uint32_t need;uint64_t addr;if(!t||!p||!s||!s->ready||s->environment_bytes<9u||s->environment_bytes>sizeof(s->environment)||!match(e,c,w,15u))return 0;need=(s->environment_bytes+15u)>>4;bx_ntvdm_multi_write_transaction_v1_initialize(t,e,c);if((uint16_t)c->ebx<need)return bx_ntvdm_cpu_result_v2_resume(&t->result,e->fault_rip+4u)&&bx_ntvdm_cpu_delta_v1_set_gpr16(&t->result.cpu_delta,3u,(uint16_t)need);addr=(uint64_t)c->es<<4;if(addr>APERTURE-s->environment_bytes)return 0;memcpy(p,s->environment,s->environment_bytes);if(!bx_ntvdm_multi_write_v1_add(&t->writes,addr,s->environment_bytes,0u)||!bx_ntvdm_cpu_result_v2_resume(&t->result,e->fault_rip+4u)||!bx_ntvdm_cpu_delta_v1_set_gpr16(&t->result.cpu_delta,3u,0u))return 0;return bx_ntvdm_multi_write_transaction_v1_preflight(t,APERTURE,s->environment_bytes);}
