#ifndef RUNTIME_OPENNT_BOP_CCPU_SAS_FACADE_H
#define RUNTIME_OPENNT_BOP_CCPU_SAS_FACADE_H

/*
 * Source-facing aliases for the existing call-scoped CCPU/SAS bridge.
 *
 * This header belongs to opennt-bop because it names the source-owned DEM
 * call record.  Its implementation reaches Bochs only through declared
 * adapter-softpc ABI and deliberately allocates no frame, mapping manager,
 * or handle table.
 */
#include "opennt-bop/dem/opennt_dem_ccpu_sas_facade.h"

typedef runtime_demhndl_call runtime_ccpu_sas_call;

#define RUNTIME_CCPU_SAS_CALL_MAGIC RUNTIME_DEMHNDL_CALL_MAGIC
#define RUNTIME_CCPU_SAS_CALL_VERSION RUNTIME_DEMHNDL_CALL_VERSION
#define runtime_ccpu_sas_call_valid runtime_demhndl_call_valid
#define runtime_ccpu_sas_invoke_body runtime_demhndl_invoke_body
#define runtime_ccpu_sas_invoke_body_with_resume runtime_demhndl_invoke_body_with_resume
#define runtime_ccpu_sas_get_ax runtime_demhndl_get_ax
#define runtime_ccpu_sas_get_bx runtime_demhndl_get_bx
#define runtime_ccpu_sas_get_cx runtime_demhndl_get_cx
#define runtime_ccpu_sas_get_dx runtime_demhndl_get_dx
#define runtime_ccpu_sas_get_si runtime_demhndl_get_si
#define runtime_ccpu_sas_get_di runtime_demhndl_get_di
#define runtime_ccpu_sas_get_ds runtime_demhndl_get_ds
#define runtime_ccpu_sas_get_es runtime_demhndl_get_es
#define runtime_ccpu_sas_set_ax runtime_demhndl_set_ax
#define runtime_ccpu_sas_set_bx runtime_demhndl_set_bx
#define runtime_ccpu_sas_set_cx runtime_demhndl_set_cx
#define runtime_ccpu_sas_set_dx runtime_demhndl_set_dx
#define runtime_ccpu_sas_set_si runtime_demhndl_set_si
#define runtime_ccpu_sas_set_di runtime_demhndl_set_di
#define runtime_ccpu_sas_set_es runtime_demhndl_set_es
#define runtime_ccpu_sas_set_cf runtime_demhndl_set_cf
#define runtime_ccpu_sas_get_vdm_addr runtime_demhndl_get_vdm_addr
#define runtime_ccpu_sas_copy_guest runtime_demhndl_copy_guest
#define runtime_ccpu_sas_write_guest runtime_demhndl_write_guest
#define runtime_ccpu_sas_get_handle runtime_demhndl_get_handle
#define runtime_ccpu_sas_close_handle runtime_demhndl_close_handle

#endif
