param(
    [Parameter(Mandatory)][string]$Pif,
    [Parameter(Mandatory)][string]$Hash,
    [Parameter(Mandatory)][string]$BuildRoot
)
$ErrorActionPreference = 'Stop'
New-Item -ItemType Directory -Force -Path $BuildRoot | Out-Null
$sample = Join-Path $BuildRoot 'sample.pif'
$invalid = Join-Path $BuildRoot 'invalid.pif'
$tampered = Join-Path $BuildRoot 'tampered.pif'
& $Pif create $sample --title Sample --program 'C:\DOS\COMMAND.COM' --directory 'C:\DOS' --arguments '/P' --config 'C:\PATCH\CONFIG.NT' --autoexec 'C:\PATCH\AUTOEXEC.NT'
if ($LASTEXITCODE -ne 0) { throw 'PIF create failed' }
& $Pif verify $sample
if ($LASTEXITCODE -ne 0) { throw 'PIF verify rejected generated bytes' }
$initial = & $Pif inspect $sample
if ($LASTEXITCODE -ne 0 -or $initial -notcontains 'TITLE=Sample') { throw 'PIF inspect did not expose generated title' }
& $Pif set $sample --title Edited --arguments '/C VER'
if ($LASTEXITCODE -ne 0) { throw 'PIF set failed' }
$edited = & $Pif inspect $sample
if ($LASTEXITCODE -ne 0 -or $edited -notcontains 'TITLE=Edited' -or $edited -notcontains 'ARGUMENTS=/C VER') { throw 'PIF edit did not persist fields' }
[IO.File]::WriteAllBytes($invalid, [Text.Encoding]::ASCII.GetBytes('not a pif'))
$priorPreference = $ErrorActionPreference
$ErrorActionPreference = 'Continue'
& $Pif verify $invalid 2>$null
$invalidExit = $LASTEXITCODE
$ErrorActionPreference = $priorPreference
if ($invalidExit -eq 0) { throw 'PIF verify accepted malformed input' }
$bytes = [IO.File]::ReadAllBytes($sample)
$bytes[10] = $bytes[10] -bxor 1
[IO.File]::WriteAllBytes($tampered, $bytes)
$ErrorActionPreference = 'Continue'
& $Pif verify $tampered 2>$null
$tamperedExit = $LASTEXITCODE
$ErrorActionPreference = $priorPreference
if ($tamperedExit -eq 0) { throw 'PIF verify accepted a bad fixed-record checksum' }
$expected = (Get-FileHash -Algorithm SHA256 -LiteralPath $sample).Hash
$actual = (& $Hash $sample).Trim()
if ($LASTEXITCODE -ne 0 -or $actual -ne $expected -or $actual -notmatch '^[0-9A-F]{64}$') { throw 'HASH output differs from SHA-256 reference' }
$ErrorActionPreference = 'Continue'
& $Hash (Join-Path $BuildRoot 'missing.bin') 2>$null
$missingHashExit = $LASTEXITCODE
$ErrorActionPreference = $priorPreference
if ($missingHashExit -eq 0) { throw 'HASH accepted a nonexistent file' }
'PASS PIF create/verify/inspect/set and HASH single-file output'
