#include "bx_ntvdm_cmd_comspec_bootstrap_service.h"
#include <string.h>

#define APERTURE UINT64_C(0x100000)
static int match(const bx_ntvdm_exception_event_v1 *e,const bx_ntvdm_cpu_state_v1 *c,const bx_ntvdm_instruction_window_v1 *w,uint8_t svc){return e&&c&&w&&bx_ntvdm_exception_event_v1_valid(e)&&bx_ntvdm_cpu_state_v1_valid(c)&&bx_ntvdm_instruction_window_v1_valid(w)&&e->vector==6u&&c->execution_mode==BX_NTVDM_CPU_EXECUTION_REAL&&w->valid_bytes>=4u&&w->bytes[0]==0xc4u&&w->bytes[1]==0xc4u&&w->bytes[2]==0x54u&&w->bytes[3]==svc&&e->fault_rip<=UINT64_MAX-4u;}
static int text(const bx_ntvdm_readonly_namespace_v1 *n,uint8_t *out,uint32_t *size){size_t i,p; if(!n||!out||!size||n->drive_index>=26u||n->files[0].path[0]!=L'\\')return 0;p=0;out[p++]='A'+n->drive_index;out[p++]=':';for(i=0;n->files[0].path[i];++i){if(n->files[0].path[i]>0x7f||p+2u>BX_NTVDM_CMD_COMSPEC_BOOTSTRAP_MAX_BYTES)return 0;out[p++]=(uint8_t)n->files[0].path[i];}out[p++]=0;*size=(uint32_t)p;return 1;}
void bx_ntvdm_cmd_comspec_bootstrap_v1_initialize(bx_ntvdm_cmd_comspec_bootstrap_v1 *v){if(v)memset(v,0,sizeof(*v));}
int bx_ntvdm_cmd_comspec_bootstrap_v1_prepare_comspec(const bx_ntvdm_readonly_namespace_v1 *n,const bx_ntvdm_exception_event_v1 *e,const bx_ntvdm_cpu_state_v1 *c,const bx_ntvdm_instruction_window_v1 *w,bx_ntvdm_guest_gather_read_action_v1 *a){uint8_t expected[BX_NTVDM_CMD_COMSPEC_BOOTSTRAP_MAX_BYTES];uint32_t bytes;bx_ntvdm_guest_range r;uint64_t addr;if(!a||!match(e,c,w,2u)||!text(n,expected,&bytes))return 0;addr=((uint64_t)c->ds<<4)+(uint16_t)c->edx;if(addr>APERTURE-bytes)return 0;r.address=addr;r.length=bytes;return bx_ntvdm_guest_gather_read_action_v1_need_read_resume(a,&r,1u,e->fault_rip+4u);}
int bx_ntvdm_cmd_comspec_bootstrap_v1_complete_comspec(const bx_ntvdm_readonly_namespace_v1 *n,const bx_ntvdm_exception_event_v1 *e,const bx_ntvdm_cpu_state_v1 *c,const bx_ntvdm_guest_gather_read_action_v1 *a,const uint8_t *b,uint64_t count,bx_ntvdm_cmd_comspec_bootstrap_v1 *s,bx_ntvdm_cpu_result_v2 *r){uint8_t expected[BX_NTVDM_CMD_COMSPEC_BOOTSTRAP_MAX_BYTES];uint32_t bytes,ax;if(!s||!r||!a||!b||!text(n,expected,&bytes)||count!=bytes||memcmp(b,expected,bytes)||!bx_ntvdm_guest_gather_read_action_v1_valid(a)||a->disposition!=BX_NTVDM_GUEST_GATHER_READ_ACTION_V1_NEED_READ||a->range_count!=1u||a->total_bytes!=bytes||a->cpu_result.disposition!=BX_NTVDM_CPU_RESULT_V2_RESUME||a->cpu_result.resume_rip!=e->fault_rip+4u)return 0;memcpy(s->environment,"COMSPEC=",8u);memcpy(s->environment+8u,expected,bytes);s->environment_bytes=8u+bytes;s->ready=1u;ax=(uint16_t)((c->eax&0xff00u)|1u);return bx_ntvdm_cpu_result_v2_resume(r,a->cpu_result.resume_rip)&&bx_ntvdm_cpu_delta_v1_set_gpr16(&r->cpu_delta,0u,(uint16_t)ax);}
int bx_ntvdm_cmd_comspec_bootstrap_v1_prepare_environment(const bx_ntvdm_exception_event_v1 *e,const bx_ntvdm_cpu_state_v1 *c,const bx_ntvdm_instruction_window_v1 *w,const bx_ntvdm_cmd_comspec_bootstrap_v1 *s,bx_ntvdm_multi_write_transaction_v1 *t,uint8_t p[BX_NTVDM_MULTI_WRITE_MAX_PAYLOAD]){uint32_t need;uint64_t addr;if(!t||!p||!s||!s->ready||s->environment_bytes<10u||s->environment_bytes>sizeof(s->environment)||!match(e,c,w,15u))return 0;need=(s->environment_bytes+15u)>>4;bx_ntvdm_multi_write_transaction_v1_initialize(t,e,c);if((uint16_t)c->ebx<need)return bx_ntvdm_cpu_result_v2_resume(&t->result,e->fault_rip+4u)&&bx_ntvdm_cpu_delta_v1_set_gpr16(&t->result.cpu_delta,3u,(uint16_t)need);addr=(uint64_t)c->es<<4;if(addr>APERTURE-s->environment_bytes)return 0;memcpy(p,s->environment,s->environment_bytes);if(!bx_ntvdm_multi_write_v1_add(&t->writes,addr,s->environment_bytes,0u)||!bx_ntvdm_cpu_result_v2_resume(&t->result,e->fault_rip+4u)||!bx_ntvdm_cpu_delta_v1_set_gpr16(&t->result.cpu_delta,3u,0u))return 0;return bx_ntvdm_multi_write_transaction_v1_preflight(t,APERTURE,s->environment_bytes);}
