#ifndef RUNNER_SHARED_APERTURE_V1_H
#define RUNNER_SHARED_APERTURE_V1_H

#include <stdint.h>

/* Fixed offsets avoid cross-bitness structure packing and pointer transfer. */
enum {
    RUNNER_SHARED_APERTURE_V1_MINIMUM_BYTES = 4096u,
    RUNNER_SHARED_APERTURE_V1_MAGIC = 0x53413450u,
    RUNNER_SHARED_APERTURE_V1_VERSION = 1u,
    RUNNER_SHARED_APERTURE_V1_OFFSET_MAGIC = 0u,
    RUNNER_SHARED_APERTURE_V1_OFFSET_VERSION = 4u,
    RUNNER_SHARED_APERTURE_V1_OFFSET_BYTES = 8u,
    RUNNER_SHARED_APERTURE_V1_OFFSET_HOST_READY = 12u,
    RUNNER_SHARED_APERTURE_V1_OFFSET_HELPER_READY = 16u,
    RUNNER_SHARED_APERTURE_V1_OFFSET_SAS_READY = 20u,
    RUNNER_SHARED_APERTURE_V1_OFFSET_HOST_PROBE = 256u,
    RUNNER_SHARED_APERTURE_V1_OFFSET_HELPER_PROBE = 512u,
    RUNNER_SHARED_APERTURE_V1_OFFSET_SAS_PROBE = 768u
};

#endif
