param(
    [Parameter(Mandatory = $true)]
    [string]$OpenNtRoot,

    [Parameter(Mandatory = $true)]
    [string]$OutputDirectory
)

$ErrorActionPreference = 'Stop'
$resolvedOpenNtRoot = (Resolve-Path -LiteralPath $OpenNtRoot).Path
$mvdmRoot = Join-Path $resolvedOpenNtRoot 'base\mvdm'
if (-not (Test-Path -LiteralPath $mvdmRoot -PathType Container)) {
    throw "OpenNT base\\mvdm source root was not found: $mvdmRoot"
}

New-Item -ItemType Directory -Force -Path $OutputDirectory | Out-Null
$descriptors = Get-ChildItem -LiteralPath $mvdmRoot -Recurse -File |
    Where-Object { $_.Name -ieq 'makefile' -or $_.Name -ieq 'sources' } |
    Sort-Object FullName

function Get-Assignment([string]$Content, [string]$Name) {
    $match = [regex]::Match($Content, "(?im)^\s*$([regex]::Escape($Name))\s*[:+?]?=\s*([^\r\n]+)")
    if ($match.Success) { return $match.Groups[1].Value.Trim() }
    return $null
}

$records = foreach ($descriptor in $descriptors) {
    $content = Get-Content -LiteralPath $descriptor.FullName -Raw
    $relative = $descriptor.FullName.Substring($mvdmRoot.Length + 1).Replace('\', '/')
    $kind = if ($descriptor.Name -ieq 'sources') { 'sources' } else { 'makefile' }
    $declared = [System.Collections.Generic.List[string]]::new()

    foreach ($name in 'dest', 'destination', 'target', 'targets', 'program', 'library', 'dll') {
        $value = Get-Assignment $content $name
        if ($null -ne $value) { $declared.Add("$name=$value") }
    }

    $targetName = Get-Assignment $content 'TARGETNAME'
    $targetExt = Get-Assignment $content 'TARGETEXT'
    if ($null -ne $targetName) {
        $declared.Add("TARGETNAME=$targetName")
        if ($null -ne $targetExt) { $declared.Add("TARGETEXT=$targetExt") }
    }

    $tools = [regex]::Matches($content, '(?im)\b(link16|link|reloc|stripz|mapsym|rc16|rc|dosmsg|binplace|masm|cl)\b') |
        ForEach-Object { $_.Value.ToLowerInvariant() } | Sort-Object -Unique
    [pscustomobject]@{
        Descriptor = $relative
        Kind = $kind
        DeclaredOutputs = @($declared)
        ToolTokens = @($tools)
        HasBuildOutputDeclaration = ($declared.Count -gt 0)
    }
}

$jsonPath = Join-Path $OutputDirectory 'opennt-mvdm-artifact-inventory.json'
$markdownPath = Join-Path $OutputDirectory 'OPENNT-MVDM-ARTIFACT-INVENTORY.md'
$records | ConvertTo-Json -Depth 4 | Set-Content -LiteralPath $jsonPath -Encoding utf8

$lines = [System.Collections.Generic.List[string]]::new()
$lines.Add('# OpenNT MVDM Artifact Inventory')
$lines.Add('')
$lines.Add('Generated by `tools/Export-OpenNtArtifactInventory.ps1` from build descriptors only.')
$lines.Add('It is a discovery manifest: a declaration is not evidence that the output has been rebuilt.')
$lines.Add('')
$lines.Add('| Descriptor | Kind | Declared outputs/targets | Tool tokens |')
$lines.Add('| --- | --- | --- | --- |')
foreach ($record in $records) {
    $outputs = if ($record.DeclaredOutputs.Count) { $record.DeclaredOutputs -join '<br>' } else { '-' }
    $tools = if ($record.ToolTokens.Count) { $record.ToolTokens -join ', ' } else { '-' }
    $lines.Add("| ``$($record.Descriptor)`` | $($record.Kind) | $outputs | $tools |")
}
$lines.Add('')
$lines.Add("Descriptor count: $($records.Count)")
$lines.Add("Declared-output count: $(($records | Where-Object HasBuildOutputDeclaration).Count)")
$lines | Set-Content -LiteralPath $markdownPath -Encoding utf8

[pscustomobject]@{
    DescriptorCount = $records.Count
    DeclaredOutputCount = ($records | Where-Object HasBuildOutputDeclaration).Count
    Json = $jsonPath
    Markdown = $markdownPath
} | ConvertTo-Json
