[CmdletBinding()]param([Parameter(Mandatory=$true)][string]$RepositoryRoot)
$ErrorActionPreference='Stop';$root=(Resolve-Path $RepositoryRoot).Path;$ops=Join-Path $root 'docs/etc/operations';$in=Join-Path $ops 'mvdm-file-recovery-ledger.tsv';$f=@(Import-Csv $in -Delimiter "`t"|Where-Object {$_.target_path -like 'dpmi32/*'}|Sort-Object target_path);if($f.Count -ne 25){throw "Expected 25 DPMI32 paths, found $($f.Count)."}
$x86=@('dpmi32/debug.c','dpmi32/dpmi32.c','dpmi32/dpmiint.c','dpmi32/dpmiselr.c','dpmi32/buffer.c','dpmi32/data.c','dpmi32/int21map.c','dpmi32/modesw.c','dpmi32/register.c','dpmi32/savestat.c','dpmi32/stack.c','dpmi32/vxd.c','dpmi32/xmem.c','dpmi32/i386/dpmi386.c','dpmi32/i386/dpmimem.c','dpmi32/i386/dpmimisc.c')
$rows=foreach($x in $f){$p=$x.target_path;$role='';$bound='adapter-mvdm-host-out/softpc; adapter-mvdm-host-out/monitor; adapter-mvdm-host-in; adapter-bochs; session guest-memory mapping manager';$sum='';$disp='';
if($p -in $x86){$role='historical-x86-dpmi32-provider-body';$sum='selected by original LINKED_INTO_MONITOR library build; retains DPMI BOP dispatch, LDT/exception/interrupt/memory and DOS transition logic; every guest address must use a bounded mapping-manager lease or copy, never raw host PVOID';$disp='x86 host-provider package prerequisite; no body enabled'}
elseif($p -in @('dpmi32/dpmimemr.c','dpmi32/dpmimscr.c')){$role='historical-risc-dpmi32-provider-body';$sum='original MIPS/PPC/Alpha provider alternative; retain source and failure-form evidence but exclude from x86/x64 recovery profile';$disp='non-x86 profile exclusion; source evidence only'}
elseif($p -match '^dpmi32/.*\.h$'){$role='historical-dpmi32-private-declaration';$sum='original DPMI32 data layout, callback and translation macro evidence; later binding may alter only pointer transport through the mapping manager';$disp='declaration and same-shaped facade prerequisite'}
else{$role='historical-dpmi32-build-description';$bound='build governance; mvdm-host';$sum='original library build selection and precompiled-header evidence only';$disp='build-description-only'}
[pscustomobject][ordered]@{file_id=$x.file_id;source_path=$p;file_kind=$x.file_kind;original_role_group=$role;provisional_component_owner='mvdm-host';required_boundary_owner=$bound;lexical_external_families='DPMI BOP; VDM_TIB/context; SoftPC/SAS; LDT/exception/interrupt; checked guest-memory mapping';original_contract_summary=$sum;provisional_disposition=$disp;state='provisional-not-enabled';evidence="$p; dpmi32/sources; dpmi32/precomp.h"}}
$rows|ConvertTo-Csv -NoTypeInformation -Delimiter "`t"|Set-Content (Join-Path $ops 'm0-t276-s20-dpmi32-file-disposition-ledger.tsv') -Encoding utf8;Write-Output "T276 S20 DPMI32 disposition generated: $($rows.Count) rows."
