[CmdletBinding()]
param([string]$RepositoryRoot = '')
if ([string]::IsNullOrWhiteSpace($RepositoryRoot)) { $RepositoryRoot = Split-Path -Parent (Split-Path -Parent $PSScriptRoot) }
$ErrorActionPreference='Stop';$ops=Join-Path (Resolve-Path -LiteralPath $RepositoryRoot).Path 'docs/etc/operations'
function ReadTsv($name){@(Import-Csv (Join-Path $ops $name) -Delimiter "`t")}
$all=ReadTsv 'm0-t276-s5-unique-call-disposition-ledger.tsv'
$work=ReadTsv 'm0-t277-s2-source-form-worklist.tsv'
$files=ReadTsv 'm0-t277-file-recovery-ledger.tsv'
$families=@();foreach($n in @('m0-t277-s3-machine-family-disposition-ledger.tsv','m0-t277-s4-dos-family-disposition-ledger.tsv','m0-t277-s5-softpc-host-control-disposition-ledger.tsv','m0-t277-s6-redir-wow-disposition-ledger.tsv')){$families+=ReadTsv $n}
if($all.Count -ne 3697 -or $work.Count -ne 325 -or $families.Count -ne 325){throw "Unexpected inputs: all=$($all.Count), work=$($work.Count), families=$($families.Count)."}
$fileByPath=@{};foreach($f in $files){$fileByPath[$f.source_path]=$f}
$reviewByBoundary=@{};foreach($f in $families){$id=$f.work_item_id -replace '^MVDM-T277-S2-','';if($reviewByBoundary.ContainsKey($id)){throw "Duplicate family review for $id"};$reviewByBoundary[$id]=$f}
$workByBoundary=@{};foreach($w in $work){$id=$w.work_item_id -replace '^MVDM-T277-S2-','';$workByBoundary[$id]=$w}
$rows=foreach($call in $all|Sort-Object disposition_id){$file=$fileByPath[$call.caller_path];if($null -eq $file){throw "No T277 file identity for $($call.caller_path)"};$review=$reviewByBoundary[$call.disposition_id];if($null -ne $review){[pscustomobject]@{effective_id='MVDM-T277-EFFECTIVE-'+$call.disposition_id;disposition_id=$call.disposition_id;call_id=$call.call_id;caller_file_id=$file.file_id;caller_path=$call.caller_path;caller_package=$call.caller_package;caller_line=$call.caller_line;symbol=$call.lexical_callee;declaration_path=$call.declaration_path;declaration_package=$call.declaration_package;caller_final_disposition=$file.final_disposition;effective_state='reviewed-future-host';family=$review.family;owner=$review.owner;retained_interface_shape=$review.retained_interface_shape;mapping_rule=$review.mapping_rule;failure_disposition=$review.failure_disposition;source_form_evidence=$review.original_provider_form;limitation='source-form reviewed; implementation not enabled';evidence=$call.evidence}}else{[pscustomobject]@{effective_id='MVDM-T277-EFFECTIVE-'+$call.disposition_id;disposition_id=$call.disposition_id;call_id=$call.call_id;caller_file_id=$file.file_id;caller_path=$call.caller_path;caller_package=$call.caller_package;caller_line=$call.caller_line;symbol=$call.lexical_callee;declaration_path=$call.declaration_path;declaration_package=$call.declaration_package;caller_final_disposition=$file.final_disposition;effective_state='non-runtime-or-profile-excluded';family='not-reviewed-not-future-host';owner='caller file final disposition excludes current host recovery';retained_interface_shape='preserved original correlation only';mapping_rule='not admitted';failure_disposition='no current provider may claim this correlation';source_form_evidence='T277 S2 eligibility excludes caller final disposition '+$file.final_disposition;limitation='not source-form reviewed because caller is not a future-host package input';evidence=$call.evidence}}}
$rows|Export-Csv (Join-Path $ops 'm0-t277-effective-source-correlation-ledger.tsv') -Delimiter "`t" -NoTypeInformation -Encoding utf8
Write-Host "Wrote $($rows.Count) T277 effective source correlations; reviewed=$(@($rows|? effective_state -eq 'reviewed-future-host').Count)."
